name: LegionPECore
version: 1.0.0
api: [1.0.0]
author: Lambo
main: Lambo\LegionPECore\Main
description: LegionPECore
commands:
#    stats:
#        description: Shows your stats
#        usage: "/stats <pvp/parkour/spleef>"
#        permission: legionpe.command.stats
    hub:
        description: Teleport to hub
        usage: "/hub"
        permission: legionpe.command.hub
#    pvp:
#        description: Get your PVP kit
#        usage: "/pvp"
#        permission: legionpe.command.pvp
# Things done at LegionPE-Delta
permission:
    legionpe:
        default: op
        description: "Allows using all commands"
        children:
            legionpe.command:
                default: op
                description: "Allows using all commands"
                children:
                    legionpe.command.stats:
                        default: op
                        description: "Shows your stats"
                    legionpe.command.hub:
                        default: op
                        description: "Teleport to hub"
                    legionpe.command.pvp:
                        default: op
                        description: "Get your PVP kit"
